name:                budget
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/budget#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2023 Author name here
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

language: GHC2021
default-extensions: OverloadedStrings, BlockArguments, OverloadedRecordDot
dependencies:
  - base >= 4.7 && < 5
  - blaze-html
  - scotty
  - persistent
  - persistent-postgresql
  - time
  - text
  - monad-logger
  - transformers
  - unliftio-core
  - mtl
  - bytestring
  - wai
  - wai-middleware-static
  - blaze-svg

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  budget:
    source-dirs:      src
    main:             Main.hs
